### ISSUE TITLE
Handle tracking events sent before init

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#109]
On load create a queue (probably a simple array is best rather than local storage as we don't want undecorated events to linger from one session to the next as e.g. f multiple users use the same machine, we may not allocate them to the right person if they persist to another session), and then flush it as and when init is called

**Comment by JakeChampion** [comment]
I think this assumes that all events on the page are meant to be tracked by o-tracking, is that a correct assumption?

Another assumption would be that the page is using the declarative tracking configuration as well as using the default tracking selectors, because otherwise o-tracking would have no knowledge about what to track. For example to track a view event, o-tracking by default tracks only elements with the data-o-tracking-view attribute on them, but this can be changed by called `oTracking.view.init({category: audio, selector: '.o-teaser__audio'})`.

If a page is wanting any custom selectors to track, then those events would still be missed.

**Comment by wheresrhys** [comment]
Such an old issue and I can't remember the exact context. I think it was because tracking was one of the last things to be initialised on page load on ft.com (with some async elements in the load waterfall, so the page would be interactive for at least some time before o-tracking was initialised) so the user could conceivably start interacting with things which trigger `oTracking` events to be be fired, and then these just disappear.

Maybe it's not so much an addition to he library, but a recommendation that sites include a very small code snippet in the head that listens for events and stores them in an array named with a convention (I think this is roughly google analytics' approach)

**Comment by JakeChampion** [comment]
Google Analytics and Snowplow both only have one way to track events which is by calling a single function. Having a single function which is used for capturing all tracking events makes it very simple to create a queue of tracking commands before the tracking library is loaded. This is because the website can create a "spy" function of the same name as the library (Google Analytics or Snowplow) and capture all the calls which were made before the library was loaded.
I.E. For Google Analytics it would look something like this:
```js
window.ga = function ga() {
  ga.queue.push(arguments);
};
ga.queue = [];
```


Unfortunately because o-tracking has multiple functions which are exposed to the website to track events as well as having multiple custom event listeners and custom event namespaces, it is really complicated to create a queue used to track events which may fire before o-tracking has loaded.

I think this would only be possible if we also made  o-tracking only have a single entrypoint to tracking data, the same way Google Analytics and Snowplow do.

Below is the type of code that would have to be written using the current o-tracking API to have a queue system in place whilst o-tracking loads.

```js
window.oTrackingCommandQueue = [];
window.oTrackingEventQueue = [];
// function to spy on
oTracking.init = function() {
	oTrackingCommandQueue.push({
		name: 'init',
		arguments: arguments
	});
};
oTracking.page = function() {
	oTrackingCommandQueue.push({
		name: 'page',
		arguments: arguments
	});
};
oTracking.click.init = function() {
	oTrackingCommandQueue.push({
		name: 'click.init',
		arguments: arguments
	});
};
oTracking.view.init = function() {
	oTrackingCommandQueue.push({
		name: 'view.init',
		arguments: arguments
	});
};
oTracking.event = function() {
	oTrackingCommandQueue.push({
		name: 'event',
		arguments: arguments
	});
};
oTracking.page.init = function() {
	oTrackingCommandQueue.push({
		name: 'page.init',
		arguments: arguments
	});
};
oTracking.event.init = function() {
	oTrackingCommandQueue.push({
		name: 'event.init',
		arguments: arguments
	});
};

// events to spy on
window.addEventListener('oTracking.page', function pageTracker(event) {
	oTrackingEventQueue.push({
		name: 'page',
		event: event
	});
});
window.addEventListener('oTracking.event', function eventTracker(event) {
	oTrackingEventQueue.push({
		name: 'event',
		event: event
	});
});
```

**Comment by JakeChampion** [comment]
Here is a draft of the changes required in o-tracking for such a queue system to work -- https://github.com/Financial-Times/o-tracking/pull/304

**Comment by JakeChampion** [comment]
@chrisbrownuk do you think this feature would be useful for products to have? It would mean they could potentially capture events which have happened prior to o-tracking being ready

**Comment by JakeChampion** [comment]
Closing this issue, we are not going to add this feature because it has not got enough product interest. If products are interested in having this feature we will likely work on a new version of o-tracking's API which makes implementing and utilizing this feature much simpler.
