### ISSUE TITLE
Handle unserialisable JSON

### ISSUE THREAD

**Issue by wheresrhys** [Financial-Times/o-tracking#115]
`Circular reference in value argument not supported` gets thrown in IE. Should we
- catch and swallow the error
- catch the error and send something more descriptive using o-errors
- include a library which handles unserialisable JSON better, and send its output as a normal tracking event
- the above, but also add some properties to indicate there's an error
- let it be
- none of the above

**Comment by JakeChampion** [comment]
I've contacted the data-platform team to see if Spoor supports circular references, which will help decide what o-tracking should do.

I've also listed my own thoughts to the potential solutions that were suggested 👍 

> `Circular reference in value argument not supported` gets thrown in IE

It is also thrown in the latest version of Chrome.

>Should we
> * catch and swallow the error

I don't think we should catch and swallow the error because that could give the team who is using o-tracking the impression that this specific piece of data is being tracked when in fact it is not.

> * catch the error and send something more descriptive using o-errors

We could do this but then the application which uses o-tracking may not be using o-errors so they would not get the error.

> * include a library which handles unserialisable JSON better, and send its output as a normal tracking event

I don't think we should handle circular references as JSON does not support them at all and each library solves circular references in their own way. If we wanted to support them, we would need to ensure that the Spoor pipeline uses the same circular reference parsing/stringifying system that o-tracking would use.

> * the above, but also add some properties to indicate there's an error

Same concern as the above question but would also potentially confuse the team using o-tracking because they would see the data would have reached Spoor correctly but see an error in their developer tools.

> * let it be

I'm leaning towards this but perhaps improving the error message to mention why we do not support circular references.

> * none of the above

**Comment by JakeChampion** [comment]
@wheresrhys Do you have a real-world example of when an application would want circular references for tracking purposes? This issue is very old (2016) so I understand if you can't remember of an example.

**Comment by JakeChampion** [comment]
The Spoor API uses [JSON.parse](https://github.com/Financial-Times/spoor-api/blob/1b784495d755a13710b2bb53270aadcf8ca9c450/server/api.js#L61), which means it does not understand circular references either.

I think because spoor-api does not understand circular references and no other requests have been made to support them, o-tracking should not support circular references either.

**Comment by wheresrhys** [comment]
Can't remember sorry - was a long time ago. The fact I came across an error in IE hints that this was an actual real world problem though.

**Comment by JakeChampion** [comment]
This will be fixed in v3 of o-tracking, the pull-request has already landed :-) https://github.com/Financial-Times/o-tracking/pull/263
