### ISSUE TITLE
Question - use of data-trackable with <a> where target is blank

### ISSUE THREAD

**Issue by katsuraku** [Financial-Times/o-tracking#189]
Tracking isn't working for an anchor tag in our codebase. I can't find much guidance on how `data-trackable` works :) 
Guessing... would you expect there to be a problem with tracking for an anchor tag with `target="_blank"` ?

**Comment by katsuraku** [comment]
This was a guess at what might have been causing a problem, turns out it was something else. We thought we were missing tracking events, but we weren't. There is a delay in receiving events for certain button clicks and maybe we should add documentation about that somewhere.

**Comment by notlee** [comment]
Some context for data-trackable attributes Adam B pointed me to: https://docs.google.com/document/d/148tz76eji1KdHyqoiX7Y-NMHEA5l8AAe2me8eM_rZ64/edit

It might be useful to improve o-tracking documentation

**Comment by JakeChampion** [comment]
Now I've learnt how o-tracking works, I can see what was happening.

o-tracking placed the events into a queue before the page unloaded (which happens when navigating to a different website) and would only send the events when the user navigates back onto the same product (which was ScoutAsia in this instance). In the new yet-to-be-released version of o-tracking we have upgraded the transport mechanism being used to one which can send events even after the page has been unloaded, which will mean this issue will not exist anymore 👍 

I will also be drawing up a diagram and some documentation about the different transport mechanisms and how the queue works 👍

**Comment by chrisbrownuk** [comment]
@JakeChampion The delayed click event delivery was also implemented to avoid the issues that were present at the time with sending events as the page was unloading.  So not just for external links.

Please also be aware that there are Spoor JSON to database table mappings that assume that the click event is coming from the destination page, so if the click event is sent from the source page Data Platform will need to be informed.  This may be tricky to handle if we have both old and new versions of click event delivery active.

**Comment by chee** [comment]
has this issue been solved by the new version of o-tracking? can we close?

**Comment by JakeChampion** [comment]
This issue has been solved, thanks for checking on this :-)

We've documented [data-trackable](https://github.com/Financial-Times/o-tracking#how-to-track-extra-click-data-using-data-trackable-attributes) and documented the logic for [when a click event is tracked](https://github.com/Financial-Times/o-tracking#otrackingclickinit) 👍

**Comment by jenniferemshepherd** [comment]
Hello! I wanted to add for anyone in Customer Products who lands on this page (because [n-tracking](https://github.com/Financial-Times/n-tracking/pull/59) uses o-tracking v2 at the time of writing), that you can resolve this issue by adding `data-o-tracking-skip-queue={true}` to your anchor tag, as we have done in `next-appetite` (will link when PR is merged).

**Comment by JakeChampion** [comment]
@jenniferemshepherd Thanks :-) We also document it in the readme, it's the second bullet point under  [oTracking.click.init](https://registry.origami.ft.com/components/o-tracking@3.0.0/readme?brand=master#otrackingclickinit) 👍
